spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bug_tracking?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    cache: false
server:
  port: 8090
  servlet:
    context-path: /
debug: true
